var namespacenet_1_1minecraft_1_1client_1_1resources =
[
    [ "data", "namespacenet_1_1minecraft_1_1client_1_1resources_1_1data.html", "namespacenet_1_1minecraft_1_1client_1_1resources_1_1data" ],
    [ "AbstractResourcePack", "classnet_1_1minecraft_1_1client_1_1resources_1_1_abstract_resource_pack.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_abstract_resource_pack" ],
    [ "DefaultPlayerSkin", "classnet_1_1minecraft_1_1client_1_1resources_1_1_default_player_skin.html", null ],
    [ "DefaultResourcePack", "classnet_1_1minecraft_1_1client_1_1resources_1_1_default_resource_pack.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_default_resource_pack" ],
    [ "FallbackResourceManager", "classnet_1_1minecraft_1_1client_1_1resources_1_1_fallback_resource_manager.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_fallback_resource_manager" ],
    [ "FileResourcePack", "classnet_1_1minecraft_1_1client_1_1resources_1_1_file_resource_pack.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_file_resource_pack" ],
    [ "FolderResourcePack", "classnet_1_1minecraft_1_1client_1_1resources_1_1_folder_resource_pack.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_folder_resource_pack" ],
    [ "FoliageColorReloadListener", "classnet_1_1minecraft_1_1client_1_1resources_1_1_foliage_color_reload_listener.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_foliage_color_reload_listener" ],
    [ "GrassColorReloadListener", "classnet_1_1minecraft_1_1client_1_1resources_1_1_grass_color_reload_listener.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_grass_color_reload_listener" ],
    [ "I18n", "classnet_1_1minecraft_1_1client_1_1resources_1_1_i18n.html", null ],
    [ "IReloadableResourceManager", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_reloadable_resource_manager.html", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_reloadable_resource_manager" ],
    [ "IResource", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource.html", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource" ],
    [ "IResourceManager", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_manager.html", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_manager" ],
    [ "IResourceManagerReloadListener", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_manager_reload_listener.html", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_manager_reload_listener" ],
    [ "IResourcePack", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_pack.html", "interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_pack" ],
    [ "Language", "classnet_1_1minecraft_1_1client_1_1resources_1_1_language.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_language" ],
    [ "LanguageManager", "classnet_1_1minecraft_1_1client_1_1resources_1_1_language_manager.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_language_manager" ],
    [ "LegacyV2Adapter", "classnet_1_1minecraft_1_1client_1_1resources_1_1_legacy_v2_adapter.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_legacy_v2_adapter" ],
    [ "Locale", "classnet_1_1minecraft_1_1client_1_1resources_1_1_locale.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_locale" ],
    [ "ResourceIndex", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_index.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_index" ],
    [ "ResourceIndexFolder", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_index_folder.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_index_folder" ],
    [ "ResourcePackFileNotFoundException", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_file_not_found_exception.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_file_not_found_exception" ],
    [ "ResourcePackListEntry", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry" ],
    [ "ResourcePackListEntryDefault", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry_default.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry_default" ],
    [ "ResourcePackListEntryFound", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry_found.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry_found" ],
    [ "ResourcePackListEntryServer", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry_server.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_list_entry_server" ],
    [ "ResourcePackRepository", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_repository.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_resource_pack_repository" ],
    [ "SimpleReloadableResourceManager", "classnet_1_1minecraft_1_1client_1_1resources_1_1_simple_reloadable_resource_manager.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_simple_reloadable_resource_manager" ],
    [ "SimpleResource", "classnet_1_1minecraft_1_1client_1_1resources_1_1_simple_resource.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_simple_resource" ],
    [ "SkinManager", "classnet_1_1minecraft_1_1client_1_1resources_1_1_skin_manager.html", "classnet_1_1minecraft_1_1client_1_1resources_1_1_skin_manager" ]
];