var namespacenet_1_1minecraft_1_1enchantment =
[
    [ "Enchantment", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment" ],
    [ "EnchantmentArrowDamage", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_damage.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_damage" ],
    [ "EnchantmentArrowFire", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_fire.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_fire" ],
    [ "EnchantmentArrowInfinite", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_infinite.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_infinite" ],
    [ "EnchantmentArrowKnockback", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_knockback.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_arrow_knockback" ],
    [ "EnchantmentBindingCurse", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_binding_curse.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_binding_curse" ],
    [ "EnchantmentDamage", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_damage.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_damage" ],
    [ "EnchantmentData", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_data.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_data" ],
    [ "EnchantmentDigging", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_digging.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_digging" ],
    [ "EnchantmentDurability", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_durability.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_durability" ],
    [ "EnchantmentFireAspect", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_fire_aspect.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_fire_aspect" ],
    [ "EnchantmentFishingSpeed", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_fishing_speed.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_fishing_speed" ],
    [ "EnchantmentFrostWalker", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_frost_walker.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_frost_walker" ],
    [ "EnchantmentHelper", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_helper.html", null ],
    [ "EnchantmentKnockback", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_knockback.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_knockback" ],
    [ "EnchantmentLootBonus", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_loot_bonus.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_loot_bonus" ],
    [ "EnchantmentMending", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_mending.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_mending" ],
    [ "EnchantmentOxygen", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_oxygen.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_oxygen" ],
    [ "EnchantmentProtection", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_protection.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_protection" ],
    [ "EnchantmentSweepingEdge", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_sweeping_edge.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_sweeping_edge" ],
    [ "EnchantmentThorns", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_thorns.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_thorns" ],
    [ "EnchantmentUntouching", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_untouching.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_untouching" ],
    [ "EnchantmentVanishingCurse", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_vanishing_curse.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_vanishing_curse" ],
    [ "EnchantmentWaterWalker", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_water_walker.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_water_walker" ],
    [ "EnchantmentWaterWorker", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_water_worker.html", "classnet_1_1minecraft_1_1enchantment_1_1_enchantment_water_worker" ],
    [ "EnumEnchantmentType", "enumnet_1_1minecraft_1_1enchantment_1_1_enum_enchantment_type.html", "enumnet_1_1minecraft_1_1enchantment_1_1_enum_enchantment_type" ]
];