var namespacenet_1_1minecraft_1_1entity_1_1passive =
[
    [ "AbstractChestHorse", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_abstract_chest_horse.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_abstract_chest_horse" ],
    [ "AbstractHorse", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_abstract_horse.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_abstract_horse" ],
    [ "EntityAmbientCreature", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_ambient_creature.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_ambient_creature" ],
    [ "EntityAnimal", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_animal.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_animal" ],
    [ "EntityBat", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_bat.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_bat" ],
    [ "EntityChicken", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_chicken.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_chicken" ],
    [ "EntityCow", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_cow.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_cow" ],
    [ "EntityDonkey", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_donkey.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_donkey" ],
    [ "EntityFlying", "interfacenet_1_1minecraft_1_1entity_1_1passive_1_1_entity_flying.html", null ],
    [ "EntityHorse", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_horse.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_horse" ],
    [ "EntityLlama", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_llama.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_llama" ],
    [ "EntityMooshroom", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_mooshroom.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_mooshroom" ],
    [ "EntityMule", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_mule.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_mule" ],
    [ "EntityOcelot", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_ocelot.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_ocelot" ],
    [ "EntityParrot", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_parrot.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_parrot" ],
    [ "EntityPig", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_pig.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_pig" ],
    [ "EntityRabbit", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_rabbit.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_rabbit" ],
    [ "EntitySheep", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_sheep.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_sheep" ],
    [ "EntityShoulderRiding", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_shoulder_riding.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_shoulder_riding" ],
    [ "EntitySkeletonHorse", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_skeleton_horse.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_skeleton_horse" ],
    [ "EntitySquid", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_squid.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_squid" ],
    [ "EntityTameable", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_tameable.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_tameable" ],
    [ "EntityVillager", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_villager.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_villager" ],
    [ "EntityWaterMob", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_water_mob.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_water_mob" ],
    [ "EntityWolf", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_wolf.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_wolf" ],
    [ "EntityZombieHorse", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_zombie_horse.html", "classnet_1_1minecraft_1_1entity_1_1passive_1_1_entity_zombie_horse" ],
    [ "HorseArmorType", "enumnet_1_1minecraft_1_1entity_1_1passive_1_1_horse_armor_type.html", "enumnet_1_1minecraft_1_1entity_1_1passive_1_1_horse_armor_type" ],
    [ "IAnimals", "interfacenet_1_1minecraft_1_1entity_1_1passive_1_1_i_animals.html", null ]
];