var searchData=
[
  ['i18n',['I18n',['../classnet_1_1minecraft_1_1client_1_1resources_1_1_i18n.html',1,'net.minecraft.client.resources.I18n'],['../classnet_1_1minecraft_1_1util_1_1text_1_1translation_1_1_i18n.html',1,'net.minecraft.util.text.translation.I18n']]],
  ['ianimals',['IAnimals',['../interfacenet_1_1minecraft_1_1entity_1_1passive_1_1_i_animals.html',1,'net::minecraft::entity::passive']]],
  ['iattribute',['IAttribute',['../interfacenet_1_1minecraft_1_1entity_1_1ai_1_1attributes_1_1_i_attribute.html',1,'net::minecraft::entity::ai::attributes']]],
  ['iattributeinstance',['IAttributeInstance',['../interfacenet_1_1minecraft_1_1entity_1_1ai_1_1attributes_1_1_i_attribute_instance.html',1,'net::minecraft::entity::ai::attributes']]],
  ['ibakedmodel',['IBakedModel',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1model_1_1_i_baked_model.html',1,'net::minecraft::client::renderer::block::model']]],
  ['ibehaviordispenseitem',['IBehaviorDispenseItem',['../interfacenet_1_1minecraft_1_1dispenser_1_1_i_behavior_dispense_item.html',1,'net::minecraft::dispenser']]],
  ['iblockaccess',['IBlockAccess',['../interfacenet_1_1minecraft_1_1world_1_1_i_block_access.html',1,'net::minecraft::world']]],
  ['iblockbehaviors',['IBlockBehaviors',['../interfacenet_1_1minecraft_1_1block_1_1state_1_1_i_block_behaviors.html',1,'net::minecraft::block::state']]],
  ['iblockcolor',['IBlockColor',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1color_1_1_i_block_color.html',1,'net::minecraft::client::renderer::color']]],
  ['iblockproperties',['IBlockProperties',['../interfacenet_1_1minecraft_1_1block_1_1state_1_1_i_block_properties.html',1,'net::minecraft::block::state']]],
  ['iblocksource',['IBlockSource',['../interfacenet_1_1minecraft_1_1dispenser_1_1_i_block_source.html',1,'net::minecraft::dispenser']]],
  ['iblockstate',['IBlockState',['../interfacenet_1_1minecraft_1_1block_1_1state_1_1_i_block_state.html',1,'net::minecraft::block::state']]],
  ['iblockstatepalette',['IBlockStatePalette',['../interfacenet_1_1minecraft_1_1world_1_1chunk_1_1_i_block_state_palette.html',1,'net::minecraft::world::chunk']]],
  ['iborderlistener',['IBorderListener',['../interfacenet_1_1minecraft_1_1world_1_1border_1_1_i_border_listener.html',1,'net::minecraft::world::border']]],
  ['icamera',['ICamera',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1culling_1_1_i_camera.html',1,'net::minecraft::client::renderer::culling']]],
  ['ichatlistener',['IChatListener',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1chat_1_1_i_chat_listener.html',1,'net::minecraft::client::gui::chat']]],
  ['ichunkgenerator',['IChunkGenerator',['../interfacenet_1_1minecraft_1_1world_1_1gen_1_1_i_chunk_generator.html',1,'net::minecraft::world::gen']]],
  ['ichunkloader',['IChunkLoader',['../interfacenet_1_1minecraft_1_1world_1_1chunk_1_1storage_1_1_i_chunk_loader.html',1,'net::minecraft::world::chunk::storage']]],
  ['ichunkprovider',['IChunkProvider',['../interfacenet_1_1minecraft_1_1world_1_1chunk_1_1_i_chunk_provider.html',1,'net::minecraft::world::chunk']]],
  ['icommand',['ICommand',['../interfacenet_1_1minecraft_1_1command_1_1_i_command.html',1,'net::minecraft::command']]],
  ['icommandlistener',['ICommandListener',['../interfacenet_1_1minecraft_1_1command_1_1_i_command_listener.html',1,'net::minecraft::command']]],
  ['icommandmanager',['ICommandManager',['../interfacenet_1_1minecraft_1_1command_1_1_i_command_manager.html',1,'net::minecraft::command']]],
  ['icommandsender',['ICommandSender',['../interfacenet_1_1minecraft_1_1command_1_1_i_command_sender.html',1,'net::minecraft::command']]],
  ['icondition',['ICondition',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1model_1_1multipart_1_1_i_condition.html',1,'net::minecraft::client::renderer::block::model::multipart']]],
  ['icontainerlistener',['IContainerListener',['../interfacenet_1_1minecraft_1_1inventory_1_1_i_container_listener.html',1,'net::minecraft::inventory']]],
  ['icrashreportdetail',['ICrashReportDetail',['../interfacenet_1_1minecraft_1_1crash_1_1_i_crash_report_detail.html',1,'net::minecraft::crash']]],
  ['icriterioninstance',['ICriterionInstance',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_instance.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger',['ICriterionTrigger',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20bredanimalstrigger_2einstance_20_3e',['ICriterionTrigger&lt; BredAnimalsTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20brewedpotiontrigger_2einstance_20_3e',['ICriterionTrigger&lt; BrewedPotionTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20changedimensiontrigger_2einstance_20_3e',['ICriterionTrigger&lt; ChangeDimensionTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20constructbeacontrigger_2einstance_20_3e',['ICriterionTrigger&lt; ConstructBeaconTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20consumeitemtrigger_2einstance_20_3e',['ICriterionTrigger&lt; ConsumeItemTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20curedzombievillagertrigger_2einstance_20_3e',['ICriterionTrigger&lt; CuredZombieVillagerTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20effectschangedtrigger_2einstance_20_3e',['ICriterionTrigger&lt; EffectsChangedTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20enchanteditemtrigger_2einstance_20_3e',['ICriterionTrigger&lt; EnchantedItemTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20enterblocktrigger_2einstance_20_3e',['ICriterionTrigger&lt; EnterBlockTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20entityhurtplayertrigger_2einstance_20_3e',['ICriterionTrigger&lt; EntityHurtPlayerTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20impossibletrigger_2einstance_20_3e',['ICriterionTrigger&lt; ImpossibleTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20inventorychangetrigger_2einstance_20_3e',['ICriterionTrigger&lt; InventoryChangeTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20itemdurabilitytrigger_2einstance_20_3e',['ICriterionTrigger&lt; ItemDurabilityTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20killedtrigger_2einstance_20_3e',['ICriterionTrigger&lt; KilledTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20levitationtrigger_2einstance_20_3e',['ICriterionTrigger&lt; LevitationTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20nethertraveltrigger_2einstance_20_3e',['ICriterionTrigger&lt; NetherTravelTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20placedblocktrigger_2einstance_20_3e',['ICriterionTrigger&lt; PlacedBlockTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20playerhurtentitytrigger_2einstance_20_3e',['ICriterionTrigger&lt; PlayerHurtEntityTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20positiontrigger_2einstance_20_3e',['ICriterionTrigger&lt; PositionTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20recipeunlockedtrigger_2einstance_20_3e',['ICriterionTrigger&lt; RecipeUnlockedTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20summonedentitytrigger_2einstance_20_3e',['ICriterionTrigger&lt; SummonedEntityTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20tameanimaltrigger_2einstance_20_3e',['ICriterionTrigger&lt; TameAnimalTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20ticktrigger_2einstance_20_3e',['ICriterionTrigger&lt; TickTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20usedendereyetrigger_2einstance_20_3e',['ICriterionTrigger&lt; UsedEnderEyeTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20usedtotemtrigger_2einstance_20_3e',['ICriterionTrigger&lt; UsedTotemTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['icriteriontrigger_3c_20villagertradetrigger_2einstance_20_3e',['ICriterionTrigger&lt; VillagerTradeTrigger.Instance &gt;',['../interfacenet_1_1minecraft_1_1advancements_1_1_i_criterion_trigger.html',1,'net::minecraft::advancements']]],
  ['idatafixer',['IDataFixer',['../interfacenet_1_1minecraft_1_1util_1_1datafix_1_1_i_data_fixer.html',1,'net::minecraft::util::datafix']]],
  ['idatawalker',['IDataWalker',['../interfacenet_1_1minecraft_1_1util_1_1datafix_1_1_i_data_walker.html',1,'net::minecraft::util::datafix']]],
  ['idebugrenderer',['IDebugRenderer',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_debug_renderer_1_1_i_debug_renderer.html',1,'net::minecraft::client::renderer::debug::DebugRenderer']]],
  ['ientitylivingdata',['IEntityLivingData',['../interfacenet_1_1minecraft_1_1entity_1_1_i_entity_living_data.html',1,'net::minecraft::entity']]],
  ['ientitymultipart',['IEntityMultiPart',['../interfacenet_1_1minecraft_1_1entity_1_1_i_entity_multi_part.html',1,'net::minecraft::entity']]],
  ['ientityownable',['IEntityOwnable',['../interfacenet_1_1minecraft_1_1entity_1_1_i_entity_ownable.html',1,'net::minecraft::entity']]],
  ['ifixabledata',['IFixableData',['../interfacenet_1_1minecraft_1_1util_1_1datafix_1_1_i_fixable_data.html',1,'net::minecraft::util::datafix']]],
  ['ifixtype',['IFixType',['../interfacenet_1_1minecraft_1_1util_1_1datafix_1_1_i_fix_type.html',1,'net::minecraft::util::datafix']]],
  ['igrowable',['IGrowable',['../interfacenet_1_1minecraft_1_1block_1_1_i_growable.html',1,'net::minecraft::block']]],
  ['iguilistentry',['IGuiListEntry',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1_gui_list_extended_1_1_i_gui_list_entry.html',1,'net::minecraft::client::gui::GuiListExtended']]],
  ['ihopper',['IHopper',['../interfacenet_1_1minecraft_1_1tileentity_1_1_i_hopper.html',1,'net::minecraft::tileentity']]],
  ['iimagebuffer',['IImageBuffer',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1_i_image_buffer.html',1,'net::minecraft::client::renderer']]],
  ['iinteractionobject',['IInteractionObject',['../interfacenet_1_1minecraft_1_1world_1_1_i_interaction_object.html',1,'net::minecraft::world']]],
  ['iinventory',['IInventory',['../interfacenet_1_1minecraft_1_1inventory_1_1_i_inventory.html',1,'net::minecraft::inventory']]],
  ['iinventorychangedlistener',['IInventoryChangedListener',['../interfacenet_1_1minecraft_1_1inventory_1_1_i_inventory_changed_listener.html',1,'net::minecraft::inventory']]],
  ['iitemcolor',['IItemColor',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1color_1_1_i_item_color.html',1,'net::minecraft::client::renderer::color']]],
  ['iitempropertygetter',['IItemPropertyGetter',['../interfacenet_1_1minecraft_1_1item_1_1_i_item_property_getter.html',1,'net::minecraft::item']]],
  ['ijsonserializable',['IJsonSerializable',['../interfacenet_1_1minecraft_1_1util_1_1_i_json_serializable.html',1,'net::minecraft::util']]],
  ['ijumpingmount',['IJumpingMount',['../interfacenet_1_1minecraft_1_1entity_1_1_i_jumping_mount.html',1,'net::minecraft::entity']]],
  ['ilistener',['IListener',['../interfacenet_1_1minecraft_1_1client_1_1multiplayer_1_1_client_advancement_manager_1_1_i_listener.html',1,'net::minecraft::client::multiplayer::ClientAdvancementManager']]],
  ['ilocatablesource',['ILocatableSource',['../interfacenet_1_1minecraft_1_1dispenser_1_1_i_locatable_source.html',1,'net::minecraft::dispenser']]],
  ['ilocation',['ILocation',['../interfacenet_1_1minecraft_1_1dispenser_1_1_i_location.html',1,'net::minecraft::dispenser']]],
  ['ilockablecontainer',['ILockableContainer',['../interfacenet_1_1minecraft_1_1world_1_1_i_lockable_container.html',1,'net::minecraft::world']]],
  ['ilootcontainer',['ILootContainer',['../interfacenet_1_1minecraft_1_1world_1_1storage_1_1loot_1_1_i_loot_container.html',1,'net::minecraft::world::storage::loot']]],
  ['imagebufferdownload',['ImageBufferDownload',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1_image_buffer_download.html',1,'net::minecraft::client::renderer']]],
  ['imerchant',['IMerchant',['../interfacenet_1_1minecraft_1_1entity_1_1_i_merchant.html',1,'net::minecraft::entity']]],
  ['imetadatasection',['IMetadataSection',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1data_1_1_i_metadata_section.html',1,'net::minecraft::client::resources::data']]],
  ['imetadatasectionserializer',['IMetadataSectionSerializer',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1data_1_1_i_metadata_section_serializer.html',1,'net::minecraft::client::resources::data']]],
  ['imetadatasectionserializer_3c_20t_20_3e',['IMetadataSectionSerializer&lt; T &gt;',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1data_1_1_i_metadata_section_serializer.html',1,'net::minecraft::client::resources::data']]],
  ['imob',['IMob',['../interfacenet_1_1minecraft_1_1entity_1_1monster_1_1_i_mob.html',1,'net::minecraft::entity::monster']]],
  ['impossibletrigger',['ImpossibleTrigger',['../classnet_1_1minecraft_1_1advancements_1_1critereon_1_1_impossible_trigger.html',1,'net::minecraft::advancements::critereon']]],
  ['imultipassmodel',['IMultipassModel',['../interfacenet_1_1minecraft_1_1client_1_1model_1_1_i_multipass_model.html',1,'net::minecraft::client::model']]],
  ['inethandler',['INetHandler',['../interfacenet_1_1minecraft_1_1network_1_1_i_net_handler.html',1,'net::minecraft::network']]],
  ['inethandlerhandshakeserver',['INetHandlerHandshakeServer',['../interfacenet_1_1minecraft_1_1network_1_1handshake_1_1_i_net_handler_handshake_server.html',1,'net::minecraft::network::handshake']]],
  ['inethandlerloginclient',['INetHandlerLoginClient',['../interfacenet_1_1minecraft_1_1network_1_1login_1_1_i_net_handler_login_client.html',1,'net::minecraft::network::login']]],
  ['inethandlerloginserver',['INetHandlerLoginServer',['../interfacenet_1_1minecraft_1_1network_1_1login_1_1_i_net_handler_login_server.html',1,'net::minecraft::network::login']]],
  ['inethandlerplayclient',['INetHandlerPlayClient',['../interfacenet_1_1minecraft_1_1network_1_1play_1_1_i_net_handler_play_client.html',1,'net::minecraft::network::play']]],
  ['inethandlerplayserver',['INetHandlerPlayServer',['../interfacenet_1_1minecraft_1_1network_1_1play_1_1_i_net_handler_play_server.html',1,'net::minecraft::network::play']]],
  ['inethandlerstatusclient',['INetHandlerStatusClient',['../interfacenet_1_1minecraft_1_1network_1_1status_1_1_i_net_handler_status_client.html',1,'net::minecraft::network::status']]],
  ['inethandlerstatusserver',['INetHandlerStatusServer',['../interfacenet_1_1minecraft_1_1network_1_1status_1_1_i_net_handler_status_server.html',1,'net::minecraft::network::status']]],
  ['ingredient',['Ingredient',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_ingredient.html',1,'net::minecraft::item::crafting']]],
  ['inpc',['INpc',['../interfacenet_1_1minecraft_1_1entity_1_1_i_npc.html',1,'net::minecraft::entity']]],
  ['intcache',['IntCache',['../classnet_1_1minecraft_1_1world_1_1gen_1_1layer_1_1_int_cache.html',1,'net::minecraft::world::gen::layer']]],
  ['integercache',['IntegerCache',['../classnet_1_1minecraft_1_1util_1_1_integer_cache.html',1,'net::minecraft::util']]],
  ['integratedplayerlist',['IntegratedPlayerList',['../classnet_1_1minecraft_1_1server_1_1integrated_1_1_integrated_player_list.html',1,'net::minecraft::server::integrated']]],
  ['integratedserver',['IntegratedServer',['../classnet_1_1minecraft_1_1server_1_1integrated_1_1_integrated_server.html',1,'net::minecraft::server::integrated']]],
  ['integratedservercommandmanager',['IntegratedServerCommandManager',['../classnet_1_1minecraft_1_1server_1_1integrated_1_1_integrated_server_command_manager.html',1,'net::minecraft::server::integrated']]],
  ['inthashmap',['IntHashMap',['../classnet_1_1minecraft_1_1util_1_1_int_hash_map.html',1,'net::minecraft::util']]],
  ['inthashmap_3c_20net_3a_3aminecraft_3a_3aclient_3a_3agui_3a_3agui_20_3e',['IntHashMap&lt; net::minecraft::client::gui::Gui &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_hash_map.html',1,'net::minecraft::util']]],
  ['inthashmap_3c_20net_3a_3aminecraft_3a_3aclient_3a_3asettings_3a_3akeybinding_20_3e',['IntHashMap&lt; net::minecraft::client::settings::KeyBinding &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_hash_map.html',1,'net::minecraft::util']]],
  ['inthashmap_3c_20net_3a_3aminecraft_3a_3aentity_3a_3aentity_20_3e',['IntHashMap&lt; net::minecraft::entity::Entity &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_hash_map.html',1,'net::minecraft::util']]],
  ['inthashmap_3c_20net_3a_3aminecraft_3a_3aentity_3a_3aentitytrackerentry_20_3e',['IntHashMap&lt; net::minecraft::entity::EntityTrackerEntry &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_hash_map.html',1,'net::minecraft::util']]],
  ['inthashmap_3c_20net_3a_3aminecraft_3a_3apathfinding_3a_3apathpoint_20_3e',['IntHashMap&lt; net::minecraft::pathfinding::PathPoint &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_hash_map.html',1,'net::minecraft::util']]],
  ['inthashmap_3c_20short_20_3e',['IntHashMap&lt; Short &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_hash_map.html',1,'net::minecraft::util']]],
  ['intidentityhashbimap',['IntIdentityHashBiMap',['../classnet_1_1minecraft_1_1util_1_1_int_identity_hash_bi_map.html',1,'net::minecraft::util']]],
  ['intidentityhashbimap_3c_20net_3a_3aminecraft_3a_3ablock_3a_3astate_3a_3aiblockstate_20_3e',['IntIdentityHashBiMap&lt; net::minecraft::block::state::IBlockState &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_identity_hash_bi_map.html',1,'net::minecraft::util']]],
  ['intidentityhashbimap_3c_20net_3a_3aminecraft_3a_3anetwork_3a_3adatasync_3a_3adataserializer_3c_3f_20_3e_20_3e',['IntIdentityHashBiMap&lt; net::minecraft::network::datasync::DataSerializer&lt;? &gt; &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_identity_hash_bi_map.html',1,'net::minecraft::util']]],
  ['intidentityhashbimap_3c_20v_20_3e',['IntIdentityHashBiMap&lt; V &gt;',['../classnet_1_1minecraft_1_1util_1_1_int_identity_hash_bi_map.html',1,'net::minecraft::util']]],
  ['invalidblockstateexception',['InvalidBlockStateException',['../classnet_1_1minecraft_1_1command_1_1_invalid_block_state_exception.html',1,'net::minecraft::command']]],
  ['inventorybasic',['InventoryBasic',['../classnet_1_1minecraft_1_1inventory_1_1_inventory_basic.html',1,'net::minecraft::inventory']]],
  ['inventorychangetrigger',['InventoryChangeTrigger',['../classnet_1_1minecraft_1_1advancements_1_1critereon_1_1_inventory_change_trigger.html',1,'net::minecraft::advancements::critereon']]],
  ['inventorycrafting',['InventoryCrafting',['../classnet_1_1minecraft_1_1inventory_1_1_inventory_crafting.html',1,'net::minecraft::inventory']]],
  ['inventorycraftresult',['InventoryCraftResult',['../classnet_1_1minecraft_1_1inventory_1_1_inventory_craft_result.html',1,'net::minecraft::inventory']]],
  ['inventoryeffectrenderer',['InventoryEffectRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1_inventory_effect_renderer.html',1,'net::minecraft::client::renderer']]],
  ['inventoryenderchest',['InventoryEnderChest',['../classnet_1_1minecraft_1_1inventory_1_1_inventory_ender_chest.html',1,'net::minecraft::inventory']]],
  ['inventoryhelper',['InventoryHelper',['../classnet_1_1minecraft_1_1inventory_1_1_inventory_helper.html',1,'net::minecraft::inventory']]],
  ['inventorylargechest',['InventoryLargeChest',['../classnet_1_1minecraft_1_1inventory_1_1_inventory_large_chest.html',1,'net::minecraft::inventory']]],
  ['inventorymerchant',['InventoryMerchant',['../classnet_1_1minecraft_1_1inventory_1_1_inventory_merchant.html',1,'net::minecraft::inventory']]],
  ['inventoryplayer',['InventoryPlayer',['../classnet_1_1minecraft_1_1entity_1_1player_1_1_inventory_player.html',1,'net::minecraft::entity::player']]],
  ['iobjectintiterable',['IObjectIntIterable',['../interfacenet_1_1minecraft_1_1util_1_1_i_object_int_iterable.html',1,'net::minecraft::util']]],
  ['iobjectintiterable_3c_20k_20_3e',['IObjectIntIterable&lt; K &gt;',['../interfacenet_1_1minecraft_1_1util_1_1_i_object_int_iterable.html',1,'net::minecraft::util']]],
  ['iobjectintiterable_3c_20t_20_3e',['IObjectIntIterable&lt; T &gt;',['../interfacenet_1_1minecraft_1_1util_1_1_i_object_int_iterable.html',1,'net::minecraft::util']]],
  ['iparticlefactory',['IParticleFactory',['../interfacenet_1_1minecraft_1_1client_1_1particle_1_1_i_particle_factory.html',1,'net::minecraft::client::particle']]],
  ['iphase',['IPhase',['../interfacenet_1_1minecraft_1_1entity_1_1boss_1_1dragon_1_1phase_1_1_i_phase.html',1,'net::minecraft::entity::boss::dragon::phase']]],
  ['iplayerfiledata',['IPlayerFileData',['../interfacenet_1_1minecraft_1_1world_1_1storage_1_1_i_player_file_data.html',1,'net::minecraft::world::storage']]],
  ['iposition',['IPosition',['../interfacenet_1_1minecraft_1_1dispenser_1_1_i_position.html',1,'net::minecraft::dispenser']]],
  ['iprogressmeter',['IProgressMeter',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1_i_progress_meter.html',1,'net::minecraft::client::gui']]],
  ['iprogressupdate',['IProgressUpdate',['../interfacenet_1_1minecraft_1_1util_1_1_i_progress_update.html',1,'net::minecraft::util']]],
  ['iprojectile',['IProjectile',['../interfacenet_1_1minecraft_1_1entity_1_1_i_projectile.html',1,'net::minecraft::entity']]],
  ['iproperty',['IProperty',['../interfacenet_1_1minecraft_1_1block_1_1properties_1_1_i_property.html',1,'net::minecraft::block::properties']]],
  ['iproperty_3c_20t_20_3e',['IProperty&lt; T &gt;',['../interfacenet_1_1minecraft_1_1block_1_1properties_1_1_i_property.html',1,'net::minecraft::block::properties']]],
  ['iproperty_3c_3f_3e',['IProperty&lt;?&gt;',['../interfacenet_1_1minecraft_1_1block_1_1properties_1_1_i_property.html',1,'net::minecraft::block::properties']]],
  ['irangedattackmob',['IRangedAttackMob',['../interfacenet_1_1minecraft_1_1entity_1_1_i_ranged_attack_mob.html',1,'net::minecraft::entity']]],
  ['irecipe',['IRecipe',['../interfacenet_1_1minecraft_1_1item_1_1crafting_1_1_i_recipe.html',1,'net::minecraft::item::crafting']]],
  ['irecipeshownlistener',['IRecipeShownListener',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1recipebook_1_1_i_recipe_shown_listener.html',1,'net::minecraft::client::gui::recipebook']]],
  ['irecipeupdatelistener',['IRecipeUpdateListener',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1recipebook_1_1_i_recipe_update_listener.html',1,'net::minecraft::client::gui::recipebook']]],
  ['iregistry',['IRegistry',['../interfacenet_1_1minecraft_1_1util_1_1registry_1_1_i_registry.html',1,'net::minecraft::util::registry']]],
  ['iregistry_3c_20net_3a_3aminecraft_3a_3aclient_3a_3arenderer_3a_3ablock_3a_3amodel_3a_3amodelresourcelocation_2c_20net_3a_3aminecraft_3a_3aclient_3a_3arenderer_3a_3ablock_3a_3amodel_3a_3aibakedmodel_20_3e',['IRegistry&lt; net::minecraft::client::renderer::block::model::ModelResourceLocation, net::minecraft::client::renderer::block::model::IBakedModel &gt;',['../interfacenet_1_1minecraft_1_1util_1_1registry_1_1_i_registry.html',1,'net::minecraft::util::registry']]],
  ['iregistry_3c_20net_3a_3aminecraft_3a_3autil_3a_3aresourcelocation_2c_20net_3a_3aminecraft_3a_3aitem_3a_3aiitempropertygetter_20_3e',['IRegistry&lt; net::minecraft::util::ResourceLocation, net::minecraft::item::IItemPropertyGetter &gt;',['../interfacenet_1_1minecraft_1_1util_1_1registry_1_1_i_registry.html',1,'net::minecraft::util::registry']]],
  ['iregistry_3c_20string_2c_20net_3a_3aminecraft_3a_3aclient_3a_3aresources_3a_3adata_3a_3ametadataserializer_2eregistration_3c_3f_20extends_20net_3a_3aminecraft_3a_3aclient_3a_3aresources_3a_3adata_3a_3aimetadatasection_20_3e_20_3e',['IRegistry&lt; String, net::minecraft::client::resources::data::MetadataSerializer.Registration&lt;? extends net::minecraft::client::resources::data::IMetadataSection &gt; &gt;',['../interfacenet_1_1minecraft_1_1util_1_1registry_1_1_i_registry.html',1,'net::minecraft::util::registry']]],
  ['ireloadableresourcemanager',['IReloadableResourceManager',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_reloadable_resource_manager.html',1,'net::minecraft::client::resources']]],
  ['irenderchunkfactory',['IRenderChunkFactory',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1chunk_1_1_i_render_chunk_factory.html',1,'net::minecraft::client::renderer::chunk']]],
  ['iresource',['IResource',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource.html',1,'net::minecraft::client::resources']]],
  ['iresourcemanager',['IResourceManager',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_manager.html',1,'net::minecraft::client::resources']]],
  ['iresourcemanagerreloadlistener',['IResourceManagerReloadListener',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_manager_reload_listener.html',1,'net::minecraft::client::resources']]],
  ['iresourcepack',['IResourcePack',['../interfacenet_1_1minecraft_1_1client_1_1resources_1_1_i_resource_pack.html',1,'net::minecraft::client::resources']]],
  ['isaveformat',['ISaveFormat',['../interfacenet_1_1minecraft_1_1world_1_1storage_1_1_i_save_format.html',1,'net::minecraft::world::storage']]],
  ['isavehandler',['ISaveHandler',['../interfacenet_1_1minecraft_1_1world_1_1storage_1_1_i_save_handler.html',1,'net::minecraft::world::storage']]],
  ['iscorecriteria',['IScoreCriteria',['../interfacenet_1_1minecraft_1_1scoreboard_1_1_i_score_criteria.html',1,'net::minecraft::scoreboard']]],
  ['isearchtree',['ISearchTree',['../interfacenet_1_1minecraft_1_1client_1_1util_1_1_i_search_tree.html',1,'net::minecraft::client::util']]],
  ['isidedinventory',['ISidedInventory',['../interfacenet_1_1minecraft_1_1inventory_1_1_i_sided_inventory.html',1,'net::minecraft::inventory']]],
  ['isnooperinfo',['ISnooperInfo',['../interfacenet_1_1minecraft_1_1profiler_1_1_i_snooper_info.html',1,'net::minecraft::profiler']]],
  ['isound',['ISound',['../interfacenet_1_1minecraft_1_1client_1_1audio_1_1_i_sound.html',1,'net::minecraft::client::audio']]],
  ['isoundeventaccessor',['ISoundEventAccessor',['../interfacenet_1_1minecraft_1_1client_1_1audio_1_1_i_sound_event_accessor.html',1,'net::minecraft::client::audio']]],
  ['isoundeventaccessor_3c_20sound_20_3e',['ISoundEventAccessor&lt; Sound &gt;',['../interfacenet_1_1minecraft_1_1client_1_1audio_1_1_i_sound_event_accessor.html',1,'net::minecraft::client::audio']]],
  ['isoundeventlistener',['ISoundEventListener',['../interfacenet_1_1minecraft_1_1client_1_1audio_1_1_i_sound_event_listener.html',1,'net::minecraft::client::audio']]],
  ['ispectatormenuobject',['ISpectatorMenuObject',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1spectator_1_1_i_spectator_menu_object.html',1,'net::minecraft::client::gui::spectator']]],
  ['ispectatormenurecipient',['ISpectatorMenuRecipient',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1spectator_1_1_i_spectator_menu_recipient.html',1,'net::minecraft::client::gui::spectator']]],
  ['ispectatormenuview',['ISpectatorMenuView',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1spectator_1_1_i_spectator_menu_view.html',1,'net::minecraft::client::gui::spectator']]],
  ['istatemapper',['IStateMapper',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1statemap_1_1_i_state_mapper.html',1,'net::minecraft::client::renderer::block::statemap']]],
  ['istattype',['IStatType',['../interfacenet_1_1minecraft_1_1stats_1_1_i_stat_type.html',1,'net::minecraft::stats']]],
  ['istringserializable',['IStringSerializable',['../interfacenet_1_1minecraft_1_1util_1_1_i_string_serializable.html',1,'net::minecraft::util']]],
  ['itabcompleter',['ITabCompleter',['../interfacenet_1_1minecraft_1_1util_1_1_i_tab_completer.html',1,'net::minecraft::util']]],
  ['item',['Item',['../classnet_1_1minecraft_1_1item_1_1_item.html',1,'net::minecraft::item']]],
  ['itemair',['ItemAir',['../classnet_1_1minecraft_1_1item_1_1_item_air.html',1,'net::minecraft::item']]],
  ['itemanvilblock',['ItemAnvilBlock',['../classnet_1_1minecraft_1_1item_1_1_item_anvil_block.html',1,'net::minecraft::item']]],
  ['itemapplegold',['ItemAppleGold',['../classnet_1_1minecraft_1_1item_1_1_item_apple_gold.html',1,'net::minecraft::item']]],
  ['itemarmor',['ItemArmor',['../classnet_1_1minecraft_1_1item_1_1_item_armor.html',1,'net::minecraft::item']]],
  ['itemarmorstand',['ItemArmorStand',['../classnet_1_1minecraft_1_1item_1_1_item_armor_stand.html',1,'net::minecraft::item']]],
  ['itemarrow',['ItemArrow',['../classnet_1_1minecraft_1_1item_1_1_item_arrow.html',1,'net::minecraft::item']]],
  ['itemaxe',['ItemAxe',['../classnet_1_1minecraft_1_1item_1_1_item_axe.html',1,'net::minecraft::item']]],
  ['itembanner',['ItemBanner',['../classnet_1_1minecraft_1_1item_1_1_item_banner.html',1,'net::minecraft::item']]],
  ['itembed',['ItemBed',['../classnet_1_1minecraft_1_1item_1_1_item_bed.html',1,'net::minecraft::item']]],
  ['itemblock',['ItemBlock',['../classnet_1_1minecraft_1_1item_1_1_item_block.html',1,'net::minecraft::item']]],
  ['itemblockspecial',['ItemBlockSpecial',['../classnet_1_1minecraft_1_1item_1_1_item_block_special.html',1,'net::minecraft::item']]],
  ['itemboat',['ItemBoat',['../classnet_1_1minecraft_1_1item_1_1_item_boat.html',1,'net::minecraft::item']]],
  ['itembook',['ItemBook',['../classnet_1_1minecraft_1_1item_1_1_item_book.html',1,'net::minecraft::item']]],
  ['itembow',['ItemBow',['../classnet_1_1minecraft_1_1item_1_1_item_bow.html',1,'net::minecraft::item']]],
  ['itembucket',['ItemBucket',['../classnet_1_1minecraft_1_1item_1_1_item_bucket.html',1,'net::minecraft::item']]],
  ['itembucketmilk',['ItemBucketMilk',['../classnet_1_1minecraft_1_1item_1_1_item_bucket_milk.html',1,'net::minecraft::item']]],
  ['itemcameratransforms',['ItemCameraTransforms',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1model_1_1_item_camera_transforms.html',1,'net::minecraft::client::renderer::block::model']]],
  ['itemcarrotonastick',['ItemCarrotOnAStick',['../classnet_1_1minecraft_1_1item_1_1_item_carrot_on_a_stick.html',1,'net::minecraft::item']]],
  ['itemchorusfruit',['ItemChorusFruit',['../classnet_1_1minecraft_1_1item_1_1_item_chorus_fruit.html',1,'net::minecraft::item']]],
  ['itemclock',['ItemClock',['../classnet_1_1minecraft_1_1item_1_1_item_clock.html',1,'net::minecraft::item']]],
  ['itemcloth',['ItemCloth',['../classnet_1_1minecraft_1_1item_1_1_item_cloth.html',1,'net::minecraft::item']]],
  ['itemcoal',['ItemCoal',['../classnet_1_1minecraft_1_1item_1_1_item_coal.html',1,'net::minecraft::item']]],
  ['itemcolored',['ItemColored',['../classnet_1_1minecraft_1_1item_1_1_item_colored.html',1,'net::minecraft::item']]],
  ['itemcolors',['ItemColors',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1color_1_1_item_colors.html',1,'net::minecraft::client::renderer::color']]],
  ['itemcompass',['ItemCompass',['../classnet_1_1minecraft_1_1item_1_1_item_compass.html',1,'net::minecraft::item']]],
  ['itemdoor',['ItemDoor',['../classnet_1_1minecraft_1_1item_1_1_item_door.html',1,'net::minecraft::item']]],
  ['itemdurabilitytrigger',['ItemDurabilityTrigger',['../classnet_1_1minecraft_1_1advancements_1_1critereon_1_1_item_durability_trigger.html',1,'net::minecraft::advancements::critereon']]],
  ['itemdye',['ItemDye',['../classnet_1_1minecraft_1_1item_1_1_item_dye.html',1,'net::minecraft::item']]],
  ['itemegg',['ItemEgg',['../classnet_1_1minecraft_1_1item_1_1_item_egg.html',1,'net::minecraft::item']]],
  ['itemelytra',['ItemElytra',['../classnet_1_1minecraft_1_1item_1_1_item_elytra.html',1,'net::minecraft::item']]],
  ['itememptymap',['ItemEmptyMap',['../classnet_1_1minecraft_1_1item_1_1_item_empty_map.html',1,'net::minecraft::item']]],
  ['itemenchantedbook',['ItemEnchantedBook',['../classnet_1_1minecraft_1_1item_1_1_item_enchanted_book.html',1,'net::minecraft::item']]],
  ['itemendcrystal',['ItemEndCrystal',['../classnet_1_1minecraft_1_1item_1_1_item_end_crystal.html',1,'net::minecraft::item']]],
  ['itemendereye',['ItemEnderEye',['../classnet_1_1minecraft_1_1item_1_1_item_ender_eye.html',1,'net::minecraft::item']]],
  ['itemenderpearl',['ItemEnderPearl',['../classnet_1_1minecraft_1_1item_1_1_item_ender_pearl.html',1,'net::minecraft::item']]],
  ['itemexpbottle',['ItemExpBottle',['../classnet_1_1minecraft_1_1item_1_1_item_exp_bottle.html',1,'net::minecraft::item']]],
  ['itemfireball',['ItemFireball',['../classnet_1_1minecraft_1_1item_1_1_item_fireball.html',1,'net::minecraft::item']]],
  ['itemfirework',['ItemFirework',['../classnet_1_1minecraft_1_1item_1_1_item_firework.html',1,'net::minecraft::item']]],
  ['itemfireworkcharge',['ItemFireworkCharge',['../classnet_1_1minecraft_1_1item_1_1_item_firework_charge.html',1,'net::minecraft::item']]],
  ['itemfishfood',['ItemFishFood',['../classnet_1_1minecraft_1_1item_1_1_item_fish_food.html',1,'net::minecraft::item']]],
  ['itemfishingrod',['ItemFishingRod',['../classnet_1_1minecraft_1_1item_1_1_item_fishing_rod.html',1,'net::minecraft::item']]],
  ['itemflintandsteel',['ItemFlintAndSteel',['../classnet_1_1minecraft_1_1item_1_1_item_flint_and_steel.html',1,'net::minecraft::item']]],
  ['itemfood',['ItemFood',['../classnet_1_1minecraft_1_1item_1_1_item_food.html',1,'net::minecraft::item']]],
  ['itemglassbottle',['ItemGlassBottle',['../classnet_1_1minecraft_1_1item_1_1_item_glass_bottle.html',1,'net::minecraft::item']]],
  ['itemhangingentity',['ItemHangingEntity',['../classnet_1_1minecraft_1_1item_1_1_item_hanging_entity.html',1,'net::minecraft::item']]],
  ['itemhoe',['ItemHoe',['../classnet_1_1minecraft_1_1item_1_1_item_hoe.html',1,'net::minecraft::item']]],
  ['itemintidtostring',['ItemIntIDToString',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_item_int_i_d_to_string.html',1,'net::minecraft::util::datafix::fixes']]],
  ['itemknowledgebook',['ItemKnowledgeBook',['../classnet_1_1minecraft_1_1item_1_1_item_knowledge_book.html',1,'net::minecraft::item']]],
  ['itemlead',['ItemLead',['../classnet_1_1minecraft_1_1item_1_1_item_lead.html',1,'net::minecraft::item']]],
  ['itemleaves',['ItemLeaves',['../classnet_1_1minecraft_1_1item_1_1_item_leaves.html',1,'net::minecraft::item']]],
  ['itemlilypad',['ItemLilyPad',['../classnet_1_1minecraft_1_1item_1_1_item_lily_pad.html',1,'net::minecraft::item']]],
  ['itemlingeringpotion',['ItemLingeringPotion',['../classnet_1_1minecraft_1_1item_1_1_item_lingering_potion.html',1,'net::minecraft::item']]],
  ['itemmap',['ItemMap',['../classnet_1_1minecraft_1_1item_1_1_item_map.html',1,'net::minecraft::item']]],
  ['itemmapbase',['ItemMapBase',['../classnet_1_1minecraft_1_1item_1_1_item_map_base.html',1,'net::minecraft::item']]],
  ['itemmeshdefinition',['ItemMeshDefinition',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1_item_mesh_definition.html',1,'net::minecraft::client::renderer']]],
  ['itemminecart',['ItemMinecart',['../classnet_1_1minecraft_1_1item_1_1_item_minecart.html',1,'net::minecraft::item']]],
  ['itemmodelgenerator',['ItemModelGenerator',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1model_1_1_item_model_generator.html',1,'net::minecraft::client::renderer::block::model']]],
  ['itemmodelmesher',['ItemModelMesher',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1_item_model_mesher.html',1,'net::minecraft::client::renderer']]],
  ['itemmonsterplacer',['ItemMonsterPlacer',['../classnet_1_1minecraft_1_1item_1_1_item_monster_placer.html',1,'net::minecraft::item']]],
  ['itemmultitexture',['ItemMultiTexture',['../classnet_1_1minecraft_1_1item_1_1_item_multi_texture.html',1,'net::minecraft::item']]],
  ['itemnametag',['ItemNameTag',['../classnet_1_1minecraft_1_1item_1_1_item_name_tag.html',1,'net::minecraft::item']]],
  ['itemoverride',['ItemOverride',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1model_1_1_item_override.html',1,'net::minecraft::client::renderer::block::model']]],
  ['itemoverridelist',['ItemOverrideList',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1model_1_1_item_override_list.html',1,'net::minecraft::client::renderer::block::model']]],
  ['itempickaxe',['ItemPickaxe',['../classnet_1_1minecraft_1_1item_1_1_item_pickaxe.html',1,'net::minecraft::item']]],
  ['itempiston',['ItemPiston',['../classnet_1_1minecraft_1_1item_1_1_item_piston.html',1,'net::minecraft::item']]],
  ['itemplateprocessor',['ITemplateProcessor',['../interfacenet_1_1minecraft_1_1world_1_1gen_1_1structure_1_1template_1_1_i_template_processor.html',1,'net::minecraft::world::gen::structure::template']]],
  ['itempotion',['ItemPotion',['../classnet_1_1minecraft_1_1item_1_1_item_potion.html',1,'net::minecraft::item']]],
  ['itempredicate',['ItemPredicate',['../classnet_1_1minecraft_1_1advancements_1_1critereon_1_1_item_predicate.html',1,'net::minecraft::advancements::critereon']]],
  ['itemrecord',['ItemRecord',['../classnet_1_1minecraft_1_1item_1_1_item_record.html',1,'net::minecraft::item']]],
  ['itemredstone',['ItemRedstone',['../classnet_1_1minecraft_1_1item_1_1_item_redstone.html',1,'net::minecraft::item']]],
  ['itemrenderer',['ItemRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1_item_renderer.html',1,'net::minecraft::client::renderer']]],
  ['items',['Items',['../classnet_1_1minecraft_1_1init_1_1_items.html',1,'net::minecraft::init']]],
  ['itemsaddle',['ItemSaddle',['../classnet_1_1minecraft_1_1item_1_1_item_saddle.html',1,'net::minecraft::item']]],
  ['itemseedfood',['ItemSeedFood',['../classnet_1_1minecraft_1_1item_1_1_item_seed_food.html',1,'net::minecraft::item']]],
  ['itemseeds',['ItemSeeds',['../classnet_1_1minecraft_1_1item_1_1_item_seeds.html',1,'net::minecraft::item']]],
  ['itemshears',['ItemShears',['../classnet_1_1minecraft_1_1item_1_1_item_shears.html',1,'net::minecraft::item']]],
  ['itemshield',['ItemShield',['../classnet_1_1minecraft_1_1item_1_1_item_shield.html',1,'net::minecraft::item']]],
  ['itemshulkerbox',['ItemShulkerBox',['../classnet_1_1minecraft_1_1item_1_1_item_shulker_box.html',1,'net::minecraft::item']]],
  ['itemsign',['ItemSign',['../classnet_1_1minecraft_1_1item_1_1_item_sign.html',1,'net::minecraft::item']]],
  ['itemsimplefoiled',['ItemSimpleFoiled',['../classnet_1_1minecraft_1_1item_1_1_item_simple_foiled.html',1,'net::minecraft::item']]],
  ['itemskull',['ItemSkull',['../classnet_1_1minecraft_1_1item_1_1_item_skull.html',1,'net::minecraft::item']]],
  ['itemslab',['ItemSlab',['../classnet_1_1minecraft_1_1item_1_1_item_slab.html',1,'net::minecraft::item']]],
  ['itemsnow',['ItemSnow',['../classnet_1_1minecraft_1_1item_1_1_item_snow.html',1,'net::minecraft::item']]],
  ['itemsnowball',['ItemSnowball',['../classnet_1_1minecraft_1_1item_1_1_item_snowball.html',1,'net::minecraft::item']]],
  ['itemsoup',['ItemSoup',['../classnet_1_1minecraft_1_1item_1_1_item_soup.html',1,'net::minecraft::item']]],
  ['itemspade',['ItemSpade',['../classnet_1_1minecraft_1_1item_1_1_item_spade.html',1,'net::minecraft::item']]],
  ['itemspectralarrow',['ItemSpectralArrow',['../classnet_1_1minecraft_1_1item_1_1_item_spectral_arrow.html',1,'net::minecraft::item']]],
  ['itemsplashpotion',['ItemSplashPotion',['../classnet_1_1minecraft_1_1item_1_1_item_splash_potion.html',1,'net::minecraft::item']]],
  ['itemstack',['ItemStack',['../classnet_1_1minecraft_1_1item_1_1_item_stack.html',1,'net::minecraft::item']]],
  ['itemstackdata',['ItemStackData',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1walkers_1_1_item_stack_data.html',1,'net::minecraft::util::datafix::walkers']]],
  ['itemstackdatalists',['ItemStackDataLists',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1walkers_1_1_item_stack_data_lists.html',1,'net::minecraft::util::datafix::walkers']]],
  ['itemstackhelper',['ItemStackHelper',['../classnet_1_1minecraft_1_1inventory_1_1_item_stack_helper.html',1,'net::minecraft::inventory']]],
  ['itemsword',['ItemSword',['../classnet_1_1minecraft_1_1item_1_1_item_sword.html',1,'net::minecraft::item']]],
  ['itemtippedarrow',['ItemTippedArrow',['../classnet_1_1minecraft_1_1item_1_1_item_tipped_arrow.html',1,'net::minecraft::item']]],
  ['itemtool',['ItemTool',['../classnet_1_1minecraft_1_1item_1_1_item_tool.html',1,'net::minecraft::item']]],
  ['itemtransformvec3f',['ItemTransformVec3f',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1block_1_1model_1_1_item_transform_vec3f.html',1,'net::minecraft::client::renderer::block::model']]],
  ['itemwritablebook',['ItemWritableBook',['../classnet_1_1minecraft_1_1item_1_1_item_writable_book.html',1,'net::minecraft::item']]],
  ['itemwrittenbook',['ItemWrittenBook',['../classnet_1_1minecraft_1_1item_1_1_item_written_book.html',1,'net::minecraft::item']]],
  ['itextcomponent',['ITextComponent',['../interfacenet_1_1minecraft_1_1util_1_1text_1_1_i_text_component.html',1,'net::minecraft::util::text']]],
  ['itexturemappopulator',['ITextureMapPopulator',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1texture_1_1_i_texture_map_populator.html',1,'net::minecraft::client::renderer::texture']]],
  ['itextureobject',['ITextureObject',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1texture_1_1_i_texture_object.html',1,'net::minecraft::client::renderer::texture']]],
  ['ithreadedfileio',['IThreadedFileIO',['../interfacenet_1_1minecraft_1_1world_1_1storage_1_1_i_threaded_file_i_o.html',1,'net::minecraft::world::storage']]],
  ['ithreadlistener',['IThreadListener',['../interfacenet_1_1minecraft_1_1util_1_1_i_thread_listener.html',1,'net::minecraft::util']]],
  ['itickable',['ITickable',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1texture_1_1_i_tickable.html',1,'net.minecraft.client.renderer.texture.ITickable'],['../interfacenet_1_1minecraft_1_1util_1_1_i_tickable.html',1,'net.minecraft.util.ITickable']]],
  ['itickablesound',['ITickableSound',['../interfacenet_1_1minecraft_1_1client_1_1audio_1_1_i_tickable_sound.html',1,'net::minecraft::client::audio']]],
  ['itickabletextureobject',['ITickableTextureObject',['../interfacenet_1_1minecraft_1_1client_1_1renderer_1_1texture_1_1_i_tickable_texture_object.html',1,'net::minecraft::client::renderer::texture']]],
  ['itileentityprovider',['ITileEntityProvider',['../interfacenet_1_1minecraft_1_1block_1_1_i_tile_entity_provider.html',1,'net::minecraft::block']]],
  ['itoast',['IToast',['../interfacenet_1_1minecraft_1_1client_1_1gui_1_1toasts_1_1_i_toast.html',1,'net::minecraft::client::gui::toasts']]],
  ['itooltipflag',['ITooltipFlag',['../interfacenet_1_1minecraft_1_1client_1_1util_1_1_i_tooltip_flag.html',1,'net::minecraft::client::util']]],
  ['itutorialstep',['ITutorialStep',['../interfacenet_1_1minecraft_1_1client_1_1tutorial_1_1_i_tutorial_step.html',1,'net::minecraft::client::tutorial']]],
  ['iworldeventlistener',['IWorldEventListener',['../interfacenet_1_1minecraft_1_1world_1_1_i_world_event_listener.html',1,'net::minecraft::world']]],
  ['iworldnameable',['IWorldNameable',['../interfacenet_1_1minecraft_1_1world_1_1_i_world_nameable.html',1,'net::minecraft::world']]]
];
